### ISSUE TITLE
graph re-render

### ISSUE THREAD

**Issue by imayobrown** [imayobrown/data2Dash#5]
Graph re-render adds extraneous lines to graph.

Before re-render:

![beforegraph](https://cloud.githubusercontent.com/assets/6884697/6641566/ec12e9a2-c974-11e4-945d-5383cfb3a820.PNG)

After re-render:

![aftergraph](https://cloud.githubusercontent.com/assets/6884697/6641577/f6f4c9f8-c974-11e4-8bd2-2cdf057d5893.PNG)

EDIT:

Graph 1 on first render: 

![graph1firstrender](https://cloud.githubusercontent.com/assets/6884697/6645183/aca44984-c990-11e4-9c00-71c05b3073fe.PNG)

Graph 2 on first render: 

![graph 2 first render](https://cloud.githubusercontent.com/assets/6884697/6645192/c47ffdd2-c990-11e4-95db-5e12e541ac44.PNG)

Graph 2 rendered after graph 1:

![graph2renderedaftergraph1](https://cloud.githubusercontent.com/assets/6884697/6645204/dab2e74a-c990-11e4-91fe-e9ceb20a3f98.PNG)

Here you can see it seems that the the graphs are overlayed on top of each other. However you get some weird straight lines (I assume this is because they go from the end of one trace to the beginning of the next that was appended to the series) and the x domains of both the graphs are not the same so some distortion appears.

**Comment by enzeart** [comment]
You STUPID bitch you can't cause an issue and then assign it to me ROFL

**Comment by imayobrown** [comment]
Watch me! No, but seriously, I have no freakin' clue what I did. I love javascript....

**Comment by imayobrown** [comment]
Tracked it to a server side script. It wasn't you after all.

**Comment by imayobrown** [comment]
Found and fixed it. For some reason the object I use in the server side script to handle the retrieval of the data and temporary storage and format of it stays in memory even after the function is over and it is no longer in scope. It's almost as if it doesn't get garbage collected after the execution of its namespace is over. Oh well, its fixed and problem is resolved.
